defaults:
  - data: 84000-parallel-sentences-no-registers
  - model: olive-cormorant-bart
  - training: basic_with_bleu
  - training_preprocess: basic
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - _self_

hydra:
  verbose: cai_garland.training
  run:
    dir: ${oc.env:CAI_TEMP_PATH}/nmt/olive-cormorant-bart/${now:%Y-%m-%d}/${now:%H-%M-%S}

# Set this to true to skip the validation step
skip_eval: false

# Overwrite the cached training and evaluation sets
overwrite_cache: false
