defaults:
  - huggingface_training_args

per_device_train_batch_size: 64
per_device_eval_batch_size: 64
gradient_accumulation_steps: 1
learning_rate: 5e-5
num_train_epochs: 3
logging_steps: 100
save_steps: 100
save_total_limit: 50
log_level: debug
evaluation_strategy: STEPS

metric_for_best_model: f1
greater_is_better: true
