defaults:
  - model: olive-cormorant-bart-x3
  - generation: medium-sized-beam
  - mode: interactive
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - _self_

hydra:
  # verbose: cai_garland
  run:
    dir: .
  output_subdir: ~

cuda: False