process_func:
  _target_: cai_garland.cli.translate.batch

# This should be specified from the command line
input_glob: ~

input_encoding: utf-8

output_dir: ./translations

# Extension of the output files (without the starting dot)
output_extension: en

# If true will output in the form:
#   preprocessed source segment
#   postprocessed translation
#   --- newline ---
# If false, outputs only the processed translated segments, one on each line
output_parallel_translation: true

# Output error messages as the translation for segments whose tokenization is too long for the encoder, instead of
#   failing with an exception
skip_long_inputs: true